version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: erica
      POSTGRES_PASSWORD: erica123
      POSTGRES_DB: marketbot
    ports:
      - "5432:5432"
    volumes:
      - erica_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erica -d marketbot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  erica_postgres_data:
