[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "npm start"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
ENABLE_DETAILED_LOGS = "true"
ANALYTICS_ENABLED = "true"

[environments.production.build]
buildCommand = "npm install --production"
startCommand = "npm start"

[environments.production.deploy]
startCommand = "npm start"
